### ISSUE TITLE
Footer not at bottom when post is short 

### ISSUE THREAD

**Issue by rmx90210** [gohugo-ananke/ananke#502]
Hello,

Thank you for this lovely theme! I noticed one issue I wanted to surface here. When a post is very short (for example, just a sentence or two), the footer isn't at the bottom. Here is a screenshot of what I'm seeing:

![image](https://user-images.githubusercontent.com/1463553/151744637-dc5a76e0-4d1c-4c78-9403-29ecae4290a4.png)

I think this may be the same issue as #370, which appears to have been closed.

**Comment by Altonss** [comment]
This trick resolved the issue:

```
body{
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

footer{
  margin-top: auto;
}
```

**Comment by Altonss** [comment]
> Hi @Altonss, Thanks for your code snippet! Would you mind giving some details about where/in which file this code should be?

I added this in a `custom.css` file! I didn't know how if it is possible to modify the tachyon css syntax in the html templates to match this, so I was not able to propose this change in a PR :)
I would be happy to read a solution if anyone has an idea!

**Comment by t-kimber** [comment]
> I added this in a `custom.css` file! I didn't know how if it is possible to modify the tachyon css syntax in the html templates to match this, so I was not able to propose this change in a PR :) I would be happy to read a solution if anyone has an idea!

Wonderful, thanks for your help @Altonss !

**Comment by Juanpam** [comment]
@Altonss I don't want to steal that snippet and make a PR. You should get the credit for that one!

**Comment by pythoninthegrass** [comment]
New-ish to hugo so this took a bit of troubleshooting. Got @Altonss' `custom.css` working with two files:
### `static/css/custom.css`
```css
body {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

footer {
  margin-top: auto;
}
```
### `hugo.toml`
```toml
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hello, World!'
theme = 'ananke'

[params]
custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]
```
Thanks for posting the workaround!! 🙏
